// File generated by FlutterFire configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvWEP8iBZapQ_mTaGG6ZwBdakG_DSQE0',
    appId: '1:487510128852:web:a282f05d2d95ff76d5a341',
    messagingSenderId: '487510128852',
    projectId: 'cooperative-gig-services-78bba',
    authDomain: 'cooperative-gig-services-78bba.firebaseapp.com',
    storageBucket: 'cooperative-gig-services-78bba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhvWEP8iBZapQ_mTaGG6ZwBdakG_DSQE0',
    appId: '1:487510128852:android:a282f05d2d95ff76d5a341',
    messagingSenderId: '487510128852',
    projectId: 'cooperative-gig-services-78bba',
    storageBucket: 'cooperative-gig-services-78bba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhvWEP8iBZapQ_mTaGG6ZwBdakG_DSQE0',
    appId: '1:487510128852:ios:a282f05d2d95ff76d5a341',
    messagingSenderId: '487510128852',
    projectId: 'cooperative-gig-services-78bba',
    storageBucket: 'cooperative-gig-services-78bba.firebasestorage.app',
    iosBundleId: 'com.brutex.cooperativeGigServices',
  );
}
